"""Generate a complete curated paper list from scratch.

Combines arXiv search, Semantic Scholar enrichment, ranking,
categorization, and Markdown output into a single pipeline.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from arxiv_curator.fieldmap import STOPWORDS
from arxiv_curator.models import EnrichedPaper
from arxiv_curator.ranker import RankedPaper


@dataclass
class GeneratedList:
    """A complete auto-generated paper list."""

    query: str
    period: str  # e.g., "2023-01 to 2026-03"
    total_papers: int
    papers_with_code: int
    top_venues: dict[str, int]
    must_reads: list[RankedPaper]  # top 5-10 by score
    categories: dict[str, list[EnrichedPaper]]  # topic -> papers
    all_papers: list[EnrichedPaper]


def _extract_github_urls(text: str) -> list[str]:
    """Extract GitHub repo URLs from text (abstract)."""
    return re.findall(r"https?://github\.com/[\w.-]+/[\w.-]+", text)


def _categorize_papers(
    papers: list[EnrichedPaper],
    query_keywords: list[str],
) -> dict[str, list[EnrichedPaper]]:
    """Categorize papers into topics based on title keywords."""
    # Build keyword frequency across all papers
    keyword_freq: dict[str, int] = {}
    paper_keywords: dict[int, list[str]] = {}

    query_lower = [k.lower() for k in query_keywords]

    for i, paper in enumerate(papers):
        words = set()
        for word in re.findall(r"[A-Za-z0-9]+", paper.title.lower()):
            if (
                len(word) > 2
                and word not in STOPWORDS
                and word not in query_lower
            ):
                words.add(word)
        paper_keywords[i] = list(words)
        for w in words:
            keyword_freq[w] = keyword_freq.get(w, 0) + 1

    # Pick top keywords that appear in 2+ papers but < 50% of total
    max_count = len(papers) * 0.5
    candidate_topics = sorted(
        [(k, v) for k, v in keyword_freq.items() if 2 <= v <= max_count],
        key=lambda x: -x[1],
    )[:10]  # max 10 categories

    categories: dict[str, list[EnrichedPaper]] = {}
    assigned: set[int] = set()

    for topic, _count in candidate_topics:
        cat_papers = []
        for i, paper in enumerate(papers):
            if i not in assigned and topic in paper_keywords.get(i, []):
                cat_papers.append(paper)
                assigned.add(i)
        if len(cat_papers) >= 2:
            categories[topic.title()] = sorted(
                cat_papers, key=lambda p: -p.citation_count
            )

    # Remaining papers go to "Other"
    other = [p for i, p in enumerate(papers) if i not in assigned]
    if other:
        categories["Other"] = sorted(other, key=lambda p: -p.citation_count)

    return categories


def build_generated_list(
    papers: list[EnrichedPaper],
    ranked: list[RankedPaper],
    query: str,
    query_keywords: list[str],
    since: str,
) -> GeneratedList:
    """Build a complete generated list."""
    # Extract date range
    dates = sorted(p.published for p in papers)
    if dates:
        period = f"{dates[0].strftime('%Y-%m')} to {dates[-1].strftime('%Y-%m')}"
    else:
        period = since

    # Count code
    papers_with_code = sum(
        1
        for p in papers
        if p.code_url or _extract_github_urls(p.abstract)
    )

    # Top venues
    venue_counts: dict[str, int] = {}
    for p in papers:
        if p.venue:
            v = p.venue.strip()
            if v:
                venue_counts[v] = venue_counts.get(v, 0) + 1
    top_venues = dict(sorted(venue_counts.items(), key=lambda x: -x[1])[:5])

    # Must reads: top papers by score
    must_reads = [r for r in ranked if r.score >= 50][:10]
    if len(must_reads) < 3:
        must_reads = ranked[:5]  # at least show top 5

    # Categorize (exclude must-read papers to avoid duplication)
    must_read_urls = {rp.paper.arxiv_url for rp in must_reads}
    remaining_papers = [p for p in papers if p.arxiv_url not in must_read_urls]
    categories = _categorize_papers(remaining_papers, query_keywords)

    return GeneratedList(
        query=query,
        period=period,
        total_papers=len(papers),
        papers_with_code=papers_with_code,
        top_venues=top_venues,
        must_reads=must_reads,
        categories=categories,
        all_papers=papers,
    )


def generated_list_to_markdown(gl: GeneratedList) -> str:
    """Convert to a complete Markdown document."""
    lines: list[str] = []

    # Title
    # Preserve acronyms (SLAM, BEV, etc.) by using the original query
    title = gl.query.replace(" AND ", " ")
    lines.append(f"# {title}")
    lines.append("")
    lines.append(
        f"> Auto-generated paper list. {gl.total_papers} papers, {gl.period}."
    )
    lines.append(
        "> Generated by [arxiv-curator](https://github.com/rsasaki0109/arxiv-curator)"
    )
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- {gl.total_papers} papers ({gl.period})")
    lines.append(f"- {gl.papers_with_code} with code implementations")
    if gl.top_venues:
        venue_str = ", ".join(
            f"{v} ({c})" for v, c in gl.top_venues.items()
        )
        lines.append(f"- Top venues: {venue_str}")
    lines.append("")

    # Must Read
    lines.append("## Must Read")
    lines.append("")
    lines.append("| Paper | Year | Citations | Venue | Code |")
    lines.append("|---|---|---|---|---|")
    for rp in gl.must_reads:
        p = rp.paper
        year = p.published.strftime("%Y")
        code = ""
        github_urls = _extract_github_urls(p.abstract)
        if p.code_url:
            code = f"[Code]({p.code_url})"
        elif github_urls:
            code = f"[Code]({github_urls[0]})"
        venue = p.venue if p.venue else ""
        lines.append(
            f"| [{p.title}]({p.arxiv_url}) | {year} | {p.citation_count:,} | {venue} | {code} |"
        )
    lines.append("")

    # Categories
    for cat_name, cat_papers in gl.categories.items():
        lines.append(f"## {cat_name}")
        lines.append("")
        lines.append("| Paper | Year | Citations | Code |")
        lines.append("|---|---|---|---|")
        for p in cat_papers:
            year = p.published.strftime("%Y")
            code = ""
            github_urls = _extract_github_urls(p.abstract)
            if p.code_url:
                code = f"[Code]({p.code_url})"
            elif github_urls:
                code = f"[Code]({github_urls[0]})"
            lines.append(
                f"| [{p.title}]({p.arxiv_url}) | {year} | {p.citation_count:,} | {code} |"
            )
        lines.append("")

    return "\n".join(lines)
